# Generated by Django 5.0.1 on 2024-01-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_id_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
